// Mocks generated by Mockito 5.4.4 from annotations
// in smartcart_ai/test/data/repositories/grocery_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:hive_flutter/hive_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:smartcart_ai/data/datasources/hive_service.dart' as _i3;
import 'package:smartcart_ai/data/models/category_model.dart' as _i6;
import 'package:smartcart_ai/data/models/grocery_item_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBox_0<E> extends _i1.SmartFake implements _i2.Box<E> {
  _FakeBox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HiveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHiveService extends _i1.Mock implements _i3.HiveService {
  MockHiveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Box<_i4.GroceryItemModel> get groceryBox => (super.noSuchMethod(
        Invocation.getter(#groceryBox),
        returnValue: _FakeBox_0<_i4.GroceryItemModel>(
          this,
          Invocation.getter(#groceryBox),
        ),
      ) as _i2.Box<_i4.GroceryItemModel>);

  @override
  _i2.Box<dynamic> get settingsBox => (super.noSuchMethod(
        Invocation.getter(#settingsBox),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#settingsBox),
        ),
      ) as _i2.Box<dynamic>);

  @override
  _i2.Box<dynamic> get historyBox => (super.noSuchMethod(
        Invocation.getter(#historyBox),
        returnValue: _FakeBox_0<dynamic>(
          this,
          Invocation.getter(#historyBox),
        ),
      ) as _i2.Box<dynamic>);

  @override
  _i5.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addItem(_i4.GroceryItemModel? item) => (super.noSuchMethod(
        Invocation.method(
          #addItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i4.GroceryItemModel> getAllItems() => (super.noSuchMethod(
        Invocation.method(
          #getAllItems,
          [],
        ),
        returnValue: <_i4.GroceryItemModel>[],
      ) as List<_i4.GroceryItemModel>);

  @override
  List<_i4.GroceryItemModel> getActiveItems() => (super.noSuchMethod(
        Invocation.method(
          #getActiveItems,
          [],
        ),
        returnValue: <_i4.GroceryItemModel>[],
      ) as List<_i4.GroceryItemModel>);

  @override
  List<_i4.GroceryItemModel> getCompletedItems() => (super.noSuchMethod(
        Invocation.method(
          #getCompletedItems,
          [],
        ),
        returnValue: <_i4.GroceryItemModel>[],
      ) as List<_i4.GroceryItemModel>);

  @override
  List<_i4.GroceryItemModel> getItemsByCategory(
          _i6.GroceryCategory? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getItemsByCategory,
          [category],
        ),
        returnValue: <_i4.GroceryItemModel>[],
      ) as List<_i4.GroceryItemModel>);

  @override
  _i5.Future<void> updateItem(_i4.GroceryItemModel? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateItem,
          [item],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteItem(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllItems() => (super.noSuchMethod(
        Invocation.method(
          #clearAllItems,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearCompletedItems() => (super.noSuchMethod(
        Invocation.method(
          #clearCompletedItems,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  T? getSetting<T>(
    String? key, {
    T? defaultValue,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getSetting,
        [key],
        {#defaultValue: defaultValue},
      )) as T?);

  @override
  _i5.Future<void> saveSetting(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSetting,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> saveToHistory(List<_i4.GroceryItemModel>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveToHistory,
          [items],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<Map<String, dynamic>> getHistory() => (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  _i5.Future<void> clearHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearHistory,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
